### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by chbndrhnns** [rienafairefr/bankinhook#1]
I tried the master and the dev branch and on both i get the following error:

```
Attaching to bankinhook_celery-beat_1, bankinhook_rabbit_1, bankinhook_db_1, bankinhook_migration_1, bankinhook_celery_1, bankinhook_hook_1
celery-beat_1  | [2017-09-11 14:01:26,931: INFO/MainProcess] beat: Starting...
db_1           | The files belonging to this database system will be owned by user "postgres".
db_1           | This user must also own the server process.
db_1           |
db_1           | The database cluster will be initialized with locale "en_US.utf8".
celery-beat_1  | [2017-09-11 14:01:26,983: ERROR/MainProcess] beat: Connection error: [Errno 111] Connection refused. Trying again in 2.0 seconds...
migration_1    | usage: manage.py [-c CONFIG_NAME] [-?] {db,bws,sync,shell,runserver} ...
db_1           | The default database encoding has accordingly been set to "UTF8".
migration_1    | manage.py: error: invalid choice: 'upgrade' (choose from 'db', 'bws', 'sync', 'shell', 'runserver')
```

**Comment by rienafairefr** [comment]
yeah it's the 

```
  migration:
    build: .
    command: python manage.py upgrade
```

step in the compose, that's not right. I think I had followed a certain tutorial, in order to have the database layer be set up you need to run all the migrations, 

maybe `python manage.py upgrade` => `python manage.py db upgrade` ?


Havent touched this project for a long time. This docker stuff I had written is not functional :-/

**Comment by rienafairefr** [comment]
I removed that migration step, in the dev branch.

Once the stack starts, you need to do the `python manage.py db upgrade` inside the `hook` docker container to do the initial migration. I think also `python manage.py bws refresh_banks` to download the data for the banks.

You also need a bankin/bridge api account (free to try) https://bridgeapi.io/

**Comment by chbndrhnns** [comment]
Yeah, I tried this.

Then it quits with

```
Attaching to bankinhook_db_1, bankinhook_celery_1, bankinhook_rabbit_1, bankinhook_celery-beat_1, bankinhook_hook_1
db_1           | LOG:  database system was shut down at 2017-09-11 14:33:02 UTC
db_1           | LOG:  MultiXact member wraparound protections are now enabled
db_1           | LOG:  database system is ready to accept connections
db_1           | LOG:  autovacuum launcher started
hook_1         | [2017-09-11 14:43:12 +0000] [1] [INFO] Starting gunicorn 19.7.1
hook_1         | [2017-09-11 14:43:12 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
hook_1         | [2017-09-11 14:43:12 +0000] [1] [INFO] Using worker: sync
hook_1         | [2017-09-11 14:43:12 +0000] [9] [INFO] Booting worker with pid: 9
celery-beat_1  | [2017-09-11 14:43:12,709: INFO/MainProcess] beat: Starting...
celery-beat_1  | [2017-09-11 14:43:12,759: ERROR/MainProcess] beat: Connection error: [Errno 111] Connection refused. Trying again in 2.0 seconds...
bankinhook_celery_1 exited with code 1
hook_1         | Traceback (most recent call last):
hook_1         |   File "/usr/local/lib/python3.4/site-packages/gunicorn/util.py", line 364, in import_app
hook_1         |     app = eval(obj, vars(mod))
hook_1         |   File "<string>", line 1, in <module>
hook_1         | NameError: name 'env' is not defined
hook_1         | Failed to find application: 'bankinhook.app'
hook_1         | [2017-09-11 14:43:13 +0000] [9] [INFO] Worker exiting (pid: 9)
hook_1         | [2017-09-11 14:43:13 +0000] [1] [INFO] Shutting down: Master
hook_1         | [2017-09-11 14:43:13 +0000] [1] [INFO] Reason: App failed to load.
bankinhook_hook_1 exited with code 4
rabbit_1       |
```

Seems like the `env` config is not found.

**Comment by rienafairefr** [comment]
Looks like a problem with the gunicorn middleware. 

See latest commit on dev, c294af5cb281d1b415d9fec2c19061d38045ae89, it starts the server through `python manage.py -c env runserver`
